Repository whamcloud/iml-agent, pull requests merged in 2019-05, with the labels that each got.

#93 Cleanup ZFS resource when moving
  chroma_agent/action_plugins/manage_targets.py
  tests/actions_plugins/test_manage_targets.py
Labels: bug

#94 Add 5.0 travis deployment
  .travis.yml
Labels: enhancement

#95 Switch sniffer from pcapy to scapy
  chroma_agent/action_plugins/manage_corosync_common.py
  chroma_agent/lib/corosync.py
  chroma_agent/lib/networking.py
  chroma_agent/version.py
  python-iml-agent.spec
  requirements.txt
  tests/test_corosync_config.py
Labels: bug, enhancement

#96 Add selinux_status action
  chroma_agent/action_plugins/agent_updates.py
  tests/actions_plugins/test_agent_updates.py
Labels: enhancement
